### ISSUE TITLE
<2. 네트워크(1)> 질문 목록

### ISSUE THREAD

**Issue by hongxeob** [Dev-CS-Study/CS-Study#12]
## 범위

- 2.1 네트워크의 기초
- 2.2 TCP/IP 4계층 모델

 ### 관련하여 본인이 잘 모르겠거나, 실제 면접시 공격 당하기 좋다고 생각하는 질문을 아래에 댓글로 남겨주세요

스터디 중 발표자를 제외한 질문자들은 **최소 한 가지 이상** 질문을 합니다
(현 페이지의 `comment`에 남긴 사전 질문을 해도 좋고, 발표자의 발표 내용 중 궁금한 것을 질문해도 좋습니다)

받은 질문에 답변을 하는 **발표자**는 아래 두 가지 방식을 사용해 답변들을 정리합니다! 
- 현 페이지에 있는 사전 질문을 받았다면  :  해당 `comment`의 `reply`로 본인이 했던 답변 + 추가되거나 보완된 내용을 요약해서 남깁니다
- 현 페이지에 없는 즉흥 질문이라면 : 따로 `comment`를 이용해 받은 질문 + 답변을 요약하여 남깁니다
---

>사전 질문들을 통해 같은 주제를 다양한 관점에서 보고, 더욱 깊은 지식 습득을 목표로 합니다!
이곳에서 질문에 관한 내용을 구체적으로 토의해도 좋습니다!

**Comment by hongxeob** [comment]
1. TCP/IP계층에서 계층을 나누는 이유는?

**Comment by dqgthb** [comment]
ThroughPut, bandwidth 의 차이는 무엇인가?

**Comment by dqgthb** [comment]
TCP에서 패킷이 드랍되었을 때, 어떤 방식으로 서로에게 드랍된 사실을 알려주는가?

**Comment by deingvelop** [comment]
![image](https://user-images.githubusercontent.com/100582309/216576552-a0ee6169-e085-4708-8806-9e1e0c2f58a6.png)

**Comment by deingvelop** [comment]
교내 인터넷은  ESS를 사용하는 건가?

**Comment by deingvelop** [comment]
처리량, 대역폭, 레이턴시, ping, 라우팅 테이블, netstat, nslookup, tracert, OSI 각 계층, handshake, ARP, ICMP, IP 중에서 각자 원하는 주제 뽑거나 랜덤으로 돌려서 발표하는 방식도 좋을 듯 합니다.

**Comment by dqgthb** [comment]
OSI 7계층 각각 Application, Session, Presentation 의 차이는 무엇이고 각각의 대표적인 프로토콜은 무엇인가?

**Comment by dqgthb** [comment]
ARP와 ICMP는 무엇인가?

**Comment by dqgthb** [comment]
중복적으로 (불필요하게) 에러검증이 일어나는 계층들은 어디인가?

**Comment by hongxeob** [comment]
> 1. TCP/IP계층에서 계층을 나누는 이유는?

- 각 계층별 처리 역할이 다르기 때문에, 계층별 간섭을 최소화할 수 있다
- 특정 계층에서 문제가 생기면, 해당 계층을 살펴보면 되기 때문에, 유지 보수가 편리하다
- 다른 계층끼리는 데이터의 전달 과정을 구체적으로 알 필요가 없기 때문에, 데이터의 캡슐화와 은닉이 가능하다

**Comment by dqgthb** [comment]
라우팅 테이블이란 무엇인가? 어떻게 사용되는가?
