### ISSUE TITLE
<1. 디자인 패턴과 프로그래밍 패러다임(1)> 질문 목록

### ISSUE THREAD

**Issue by hongxeob** [Dev-CS-Study/CS-Study#6]
## 범위

- 1.1.1 싱글톤 팩턴
- 1.1.2 팩토리 패턴
- 1.1.3 전략 패턴
- 1.1.4 옵저버 패턴
- 1.1.5 프록시 패턴과 프록시 서버
- 1.1.6 이터레이터 패턴
- 1.1.7 노출모듈 패턴
- 1.1.8 MVC 패턴
- 1.1.9 MVP 패턴
- 1.1.10 MVVM 패턴
- 1.2.1 선언형과 함수형 프로다이밍
- 1.2.2 객체지향 프로그래밍
- 1.2.3 절차형 프로그래밍
- 1.2.4 패러다임의 혼합

 ### 관련하여 본인이 잘 모르겠거나, 실제 면접시 공격 당하기 좋다고 생각하는 질문을 아래에 댓글로 남겨주세요

스터디 중 발표자를 제외한 질문자들은 **최소 한 가지 이상** 질문을 합니다
(현 페이지의 `comment`에 남긴 사전 질문을 해도 좋고, 발표자의 발표 내용 중 궁금한 것을 질문해도 좋습니다)

받은 질문에 답변을 하는 **발표자**는 아래 두 가지 방식을 사용해 답변들을 정리합니다! 
- 현 페이지에 있는 사전 질문을 받았다면  :  해당 `comment`의 `reply`로 본인이 했던 답변 + 추가되거나 보완된 내용을 요약해서 남깁니다
- 현 페이지에 없는 즉흥 질문이라면 : 따로 `comment`를 이용해 받은 질문 + 답변을 요약하여 남깁니다
---

>사전 질문들을 통해 같은 주제를 다양한 관점에서 보고, 더욱 깊은 지식 습득을 목표로 합니다!
이곳에서 질문에 관한 내용을 구체적으로 토의해도 좋습니다!

**Comment by deingvelop** [comment]
싱글톤 패턴은 GoF 디자인 패턴의 구분에 따라 생성 패턴, 구조 패턴, 행동 패턴 중 하나에 속한다. 셋 중 어느 패턴에 속할 것 같은가? 그 이유는?

**Comment by deingvelop** [comment]
Java가 다중 상속을 막는 이유?
dedly diamond death (죽음의 다이아몬드)을 피하기 위해

**Comment by hongxeob** [comment]
> 1. 전략 패턴과 팩토리 패턴 차이
> 2. 스프링 MVC 패턴에서 Repository, Service, DTO,DAO등은 어떤 계층에 속하고, 그렇게 된 이유는 무엇인가?
> 3. 상속의 형태 중 `extends`와 `implements`의 차이점은 무엇인가?

Q: `implements`가 다중 상속이 가능한 이유? 
A : 우선 자바 **클래스**는 부모 클래스 하나만 상속할수 있다. 
`extends` 를 이용한 클래스 상속은 하나만 되고 두 개 이상은  **interface**만 된다
 interface는 실질적인 구현이 이루어지지 않고 메소드에 대한 선언만 하고 있기 때문에 다중 상속(구현)이 가능하다
메소드가 겹치더라도 최종 구현 부분은 구현 객체에서 이루어질 것이기 때문에 **interface**는 다중 상속이 가능하다

### 결론 : 인터페이스는 구현된 메서드가 없기 때문에, 다중상속이 가능하다

참고 페이지 
- [[Java] 자바의 다중상속 (feat. 인터페이스와 추상클래스)](https://junior-datalist.tistory.com/213)
- [자바 다중상속 인터페이스 다루는 방법](https://mainia.tistory.com/2139)

**Comment by dqgthb** [comment]
LSP 주의점: 단순히 부모 타입에는 자식 객체를 할당할 수 있지만, 자식 타입에는 부모 객체를 할당할 수 없다는 요지가 아니다.
부모 인터페이스에 주어진 명세를 자식이 일관되게 따라야 한다는 원칙이다.
예를 들어, 부모 인터페이스에 .run 이라는 함수가 주로 앞으로 전진하며 뛰어간다면, 갑자기 자식 객체에서 .run을 뒤로 뛰어가는 함수로 구현하면 LSP에 위배된다.

**Comment by dqgthb** [comment]
> 의존성 주입이란 무엇인가? 의존성 주입 원칙에는 어떠한 것들이 있는가? 

의존성 주입이란 임의의 객체나 함수 A가 그것이 'depends on'하는 다른 객체 및 함수B를 'receive'하는 디자인패턴의 일종이다. Inversion of Control의 한 형태이며, loosely coupled programs을 만들 수 있다는 장점이 있다. A가 B의 생성에 대해 전혀 몰라도 되고, Injector가 B의 생성을 대신 책임지고 A에게 주입한다.

 의존성 주입 원칙에는

1. High-level module들은 Low-level module에게서 아무것도 import하지 말아야 한다. 둘 다 Interface에 의존해야 한다.
2. 추상화는 구현에 의존하지 말아야 한다. 구현은 추상화에 의존해야 한다.

와 같은 것들이 있다.

> 의존성 주입을 하는 대표적인 디자인 패턴은 어떠한 것들이 있는가?

의존성 주입 자체가 디자인 패턴이라는 사람도 있고, 의존성 주입이 A set of design patterns라는 사람이 있고, strategy pattern, factory pattern이 DI를 이루기 위한 디자인 패턴들이라는 사람들도 있고... 질문이 모호하다.
